# Generated by Django 4.0.2 on 2022-03-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_exerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exerpt',
            field=models.TextField(max_length=150),
        ),
    ]
