# Generated by Django 4.0.2 on 2022-04-02 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_comments_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uimage', models.ImageField(upload_to='userimage')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userimg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
