# Generated by Django 4.0.2 on 2022-04-02 04:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_userimg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserImg',
            new_name='UserImage',
        ),
    ]
