# Generated by Django 4.0.2 on 2022-04-03 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_rename_userimg_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userimg', to=settings.AUTH_USER_MODEL),
        ),
    ]
