# Generated by Django 4.0.2 on 2022-06-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_like_alter_userimage_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
