# Generated by Django 4.0.2 on 2022-06-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_likespost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='aboutme',
            field=models.TextField(default=None),
        ),
    ]
