# Generated by Django 4.0.2 on 2022-07-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_userimage_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='designation',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='userimage',
            name='instagram',
            field=models.URLField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='userimage',
            name='twiter',
            field=models.URLField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='userimage',
            name='youtube',
            field=models.URLField(default='#', max_length=300),
        ),
    ]
