# Generated by Django 4.0.2 on 2022-09-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
